name: Build Rust Compiler Toolchain (WebAssembly WASM)

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-rust-compiler.yml'
      - 'rust-compiler/**'

jobs:
  build-compiler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Build Rust Compiler for WASI
        run: |
          cargo build --release --target wasm32-unknown-unknown

      - name: Package WASM Output
        run: |
          mkdir -p release-dist
          cp target/wasm32-unknown-unknown/release/rust-compiler.wasm release-dist/rust-compiler.wasm
          echo "Hasil Ukuran File WASM Compiler:"
          ls -lh release-dist/rust-compiler.wasm

      - name: Upload WASM Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: rust-compiler-wasm
          path: release-dist/rust-compiler.wasm
